//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public Article()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Point { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public int AuthorId { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual Author Author { get; set; }
    }
}
