//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Id { get; set; }
        public int ArticleId { get; set; }
        public string Text { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public int AuthorId { get; set; }

        public string AuthorName { set; get; }
    
        public virtual Author Author { get; set; }
    }
}
